services:
  watcher:
    image: marpteam/marp-cli:v4.2.3
    environment:
      # Replace with $(id -u):$(id -g)
      - MARP_USER=1000:1000
    ports:
      - 37717:37717
    volumes:
      - ./slides/:/home/marp/app
    command: --theme-set title.css -w main.md
