services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - 5432:5432

  app:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/app
    ports:
      - 8000:8000

